repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        types_or: [c, c++]
        args: [--dry-run, --Werror]

      - id: make
        name: make
        entry: make
        language: system
        pass_filenames: false